### ISSUE TITLE
Try to eliminate the necessity of $name

### ISSUE THREAD

**Issue by melanke** [simplitech/simpli-web-sdk#10]
Let´s discuss about this

**Comment by ftgibran** [comment]
Actually, the default value of `$name` is `this.constructor.name`. In the develpment mode it works perfectly. However, when the project is compiled into the minefy js, the `$name` loses its functionality. 

If you do not know, the `$name` is used mainly to indicate to the translator the model name. 

To summarise, there is no way to eliminate the `$name` field because it is used for string reference.

**Comment by melanke** [comment]
Maybe we can put it on the schema, the json is bloated with many $ props, I know we can `@Exclude` it, but if we can eliminate it would be better for the class readability
