### ISSUE TITLE
improve css

### ISSUE THREAD

**Issue by melanke** [simplitech/simpli-web-sdk#8]
- use linelay
- organize class names to be really unique using a prefix
- put as many class as possible in the components to be able to fully customize
- use as less styling as possible and dont use important
- try not to use position relative or absolute

**Comment by ftgibran** [comment]
I think it is not a good idea to include the linelay in the library because it is heavy and should be optional for the user. Therefore, I prefer the linelay be included directly in the project (simpli-cli includes linelay in the project by default). 

For the other requests, the CSS classes need to be reviewed individually and carefully to apply them.

**Comment by melanke** [comment]
About linelay, we will use purgeCss to make the final compilation smaller. We can discuss about this, but we should use more flex at least, maybe copy only the linelay classes we need.
